# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b55d0accc1393ed62688bedeed839187c652e0dc483c79d10acb4c850f8104c073115395121b4cc48554842a9e6f6c08d1f2e3c86adce99fc3de75731ce398a

test:
  secret_key_base: 1173292e268e5d3a12f63e71dbe5a1b4619c63d15098cd7f8687a9d135afa706386cc86d22b35c612901284b178be1c260f1dde14bfeabad5af7d89dfe5fdc1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
